
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'මාව පාලනය කරන්න පුළුවන් මම හදපු කෙනාට විතරයි.\nඒ හින්ද මම මේ chat එකේ දි වැඩ නෑ.\nචැට් id -: <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Hi!\nමම <b>ART OF TECH LEECHER</b> බොට් !\nPowered by @Art_of_tech.",
    'PASS_REQUIRED' : '\n\n<code>/pass</code> ගහලා bot ගෙ password එක දෙන්න.',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Leech Status</b>',
    'LEECH_LIST_FORMAT' : 'Name: <code>{name}</code>\nStatus: {status}\nID: <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "මෙය වැඩ ද කියා check කරමින් පවති...",
    'ARIA2_DOWNLOAD_STATUS' : "Downloading : <code>{name}</code>\n{block} {percentage}\nSize : {total_size}\nDOWNLOAD : {download_speed} / UPLOAD : {upload_speed}\nSeeder : {seeder}\nETA : {eta}\nID : <code>{gid}</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : 'File downloaded : <code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : 'Download canceled : <code>{name}</code>',
    'ARIA2_DEAD_LINK' : 'Download auto canceled : <code>{name}</code>\nYour Torrent/Link is Dead.',
    'ARIA2_NO_URI' : 'මේක වැඩ නැති link එකක් 💔',
    'UPLOADING_FILE' : 'Uploading : <code>{name}</code>',
    'UPLOADING_PROGRESS' : 'Uploading : <code>{name}</code>\n{block} {percentage}%\nSize : {size}\nUP : {upload_speed}/s\nETA : {eta}',
    'UPLOAD_FAILED_FILE_MISSING' : 'Upload : Failed. file not found.\n<code>{name}</code>',
    'GENERATE_THUMBNAIL' : 'Thumbnail : Generating.\n<code>{name}</code>',
    'SPLIT_FILE' : 'Spliting : <code>{name}</code>',
    'SPLIT_FAILED' : 'Split : Failed.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'Set <code>/{cmd_set_thumbnail}</code> as your photo caption.',
    'THUMBNAIL_DOWNLOADING' : 'Downloading thumbnail.',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail download.',
    'THUMBNAIL_APPLIED' : 'Thumbnail applied.',
    'THUMBNAIL_DELETING' : 'Deleting thumbnail.',
    'THUMBNAIL_RESET' : 'Thumbnail reset.',
    'UPLOAD_AS_DOC' : 'Upload as document set to {status}.',
    'UPLOAD_AS_ZIP' : 'Upload as zip file set to {status}.',
    'TRACKER_RESET' : 'Default torrent tracker reset.',
    'TRACKER_APPLIED' : 'Default torrent tracker applied.',
    'HELP_MESSAGE_HEADER' : '<b>Bot Command</b>',
    'NO_HELP_INFO' : 'මොකුත් නෑ',
    'COMMAND_START' : 'Bot start කරන්න',
    'COMMAND_PASSWORD' : 'Password එකෙන් මාව පනගන්වන්න',
    'COMMAND_HELP' : 'මේ help මෙනු එක',
    'COMMAND_LEECH' : 'Torrent link එකක් telegram එකට upload කරගන්න.',
    'COMMAND_CANCEL_LEECH' : 'ඔය දාපු වැඩේ cancal කරන්න',
    'COMMAND_LEECH_LIST' : 'Uploading වෙන list එක',
    'COMMAND_SET_THUMBNAIL' : 'Thumbnail එකක් දාන්න.',
    'COMMAND_RESET_THUMBNAIL' : 'Thumbnail එක අයින් කරන්න',
    'COMMAND_UPLOAD_AS_DOC' : 'Doc එකක් විදිහට upload කරන්න 📃',
    'COMMAND_UPLOAD_AS_ZIP' : 'Zip එකක් විදිහට upload කරන්න 🤐',
    'COMMAND_SET_TRACKER' : 'Settings default කරන්න',
    'BLOCK_EMPTY' : "░",
    "BLOCK_FILLED" : "█"
})
